const SUPPORT_CARDS = [
  { name: "Tokai Teio (Dream Big!)", type: "Speed" },
  { name: "Super Creek (Piece of Mind)", type: "Stamina" },
  { name: "Mayano Top Gun (Cute + Cute = )", type: "Stamina" },
  { name: "Sweep Tosho (Lamplit Training of a Witch-to-be)", type: "Speed" },
  { name: "Kitasan Black (Fire at My Heels)", type: "Speed" },
  { name: "Zenno Rob Roy (The Perfect Book for You)", type: "Stamina" },
  { name: "Vodka (Wild Rider)", type: "Power" },
  { name: "Fine Motion (Wave of Gratitude)", type: "Wit" },
  { name: "Nishino Flower (Even the Littlest Bud)", type: "Speed" },
  { name: "Special Week (The Setting Sun And Rising Stars)", type: "Speed" },
  { name: "Silence Suzuka (Beyond This Shining Moment)", type: "Speed" },
  { name: "Sakura Bakushin O (Eat Fast! Yum Fast!)", type: "Speed" },
  { name: "El Condor Pasa (Champions Passion)", type: "Power" },
  { name: "Biko Pegasus (Double Carrot Punch!)", type: "Speed" },
  { name: "Eishin Flash (500 am-Right on Schedule)", type: "Speed" },
  { name: "Tazuna Hayakawa (Tracen Reception)", type: "Scenario" },
  { name: "Twin Turbo (Turbo Booooost!)", type: "Speed" },
  { name: "Mejiro McQueen (Your Team Ace)", type: "Stamina" },
  { name: "Fuji Kiseki (Well, Look Who's Home)", type: "Wit" },
  { name: "Marvelous Sunday (A Marvelous ☆ Plan)", type: "Wit" },
  { name: "Symboli Rudolf (Tracen Academy)", type: "Wit" },
  { name: "King Halo (First-Rate Plan)", type: "Speed" },
  { name: "Daiwa Scarlet (Nothing Hard Work Can't Solve!)", type: "Wit" },
  { name: "Oguri Cap (Get Lots of Hugs for Me)", type: "Power" },
  { name: "Narita Taishin (Poolside High Tides)", type: "Speed" },
  { name: "Rice Shower (Showered In Joy)", type: "Stamina" }
];
